"""Public API for the MNIST MLP3 tangent-space RG experiment suite."""

from .capture import (
    finalize_step_capture,
    list_capture_files,
    load_step_capture,
    prepare_step_capture,
    replay_calibrated_step,
)
from .checkpoints import (
    AnalysisCheckpointRef,
    ensure_tail_checkpoint_cache,
    finalize_tail_checkpoint_cache,
    format_analysis_checkpoint_name,
    inspect_full_checkpoint,
    list_analysis_checkpoints,
    load_analysis_checkpoint,
    load_verified_tail_checkpoint_refs,
    parse_analysis_checkpoint_name,
    quarantine_tail_checkpoint_cache_after_boundary,
    save_tail_checkpoint,
    verify_tail_checkpoint_cache,
    verify_tail_checkpoint_cache_prefix,
)
from .config import (
    AdamWProfile,
    MuonClipRMSProfile,
    MuonProfile,
    SUPPORTED_OPTIMIZERS,
    TangentRGConfig,
    config_from_mapping,
    load_config,
)
from .muonclip import (
    MuonClipRMSWithAuxAdamW,
    QK_CLIPPING_APPLICABLE,
    matrix_update_components,
)
from .protocol import (
    AnalysisPlan,
    BurstWindow,
    RunLayout,
    TAIL_CHECKPOINT_COUNT,
    TailCheckpointLayout,
    build_analysis_plan,
    log_spaced_epochs,
    make_run_layout,
    make_tail_checkpoint_layout,
    tail_checkpoint_epochs,
    validate_disjoint_checkpoint_layouts,
)
from .training import (
    TrainingResult,
    build_training_optimizer,
    run_training,
    scheduled_learning_rates,
    set_scheduled_learning_rates,
)
from . import weight_quotients


__all__ = [
    "AdamWProfile",
    "AnalysisCheckpointRef",
    "AnalysisPlan",
    "BurstWindow",
    "MuonClipRMSProfile",
    "MuonClipRMSWithAuxAdamW",
    "MuonProfile",
    "QK_CLIPPING_APPLICABLE",
    "RunLayout",
    "TAIL_CHECKPOINT_COUNT",
    "TailCheckpointLayout",
    "SUPPORTED_OPTIMIZERS",
    "TangentRGConfig",
    "TrainingResult",
    "build_analysis_plan",
    "build_training_optimizer",
    "config_from_mapping",
    "ensure_tail_checkpoint_cache",
    "finalize_tail_checkpoint_cache",
    "finalize_step_capture",
    "format_analysis_checkpoint_name",
    "inspect_full_checkpoint",
    "list_analysis_checkpoints",
    "load_analysis_checkpoint",
    "load_verified_tail_checkpoint_refs",
    "list_capture_files",
    "load_config",
    "load_step_capture",
    "log_spaced_epochs",
    "make_run_layout",
    "make_tail_checkpoint_layout",
    "matrix_update_components",
    "parse_analysis_checkpoint_name",
    "prepare_step_capture",
    "quarantine_tail_checkpoint_cache_after_boundary",
    "replay_calibrated_step",
    "run_training",
    "scheduled_learning_rates",
    "save_tail_checkpoint",
    "set_scheduled_learning_rates",
    "tail_checkpoint_epochs",
    "verify_tail_checkpoint_cache",
    "verify_tail_checkpoint_cache_prefix",
    "validate_disjoint_checkpoint_layouts",
    "weight_quotients",
]
